catalog:
  '@playwright/test': ^1.61.1
catalogMode: prefer

catalogs:
  build:
    '@nuxt/devtools': ^3.2.4
    '@nuxt/eslint': ^1.16.0
    '@nuxtjs/color-mode': ^4.0.1
    '@pinia/nuxt': ^0.11.3
    '@unocss/eslint-config': ^66.7.4
    '@unocss/nuxt': ^66.7.4
    '@vueuse/nuxt': ^14.3.0
    nuxt: ^4.4.8
    unocss: ^66.7.4
  dev:
    '@antfu/eslint-config': ^8.3.0
    eslint: ^10.6.0
    eslint-plugin-format: ^2.0.1
    typescript: ^6.0.3
    vue-tsc: ^3.3.6
  frontend:
    '@vueuse/core': ^14.3.0
    es-toolkit: ^1.49.0
    pinia: ^3.0.4
    vue: ^3.5.39
  icons:
    '@iconify-json/carbon': ^1.2.24

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

shellEmulator: true

trustPolicy: no-downgrade
